export const GLOBALS = {
  API: {
    LOGIN: "users/login",
    REGISTER: "users/signup",
    FILES: "files?user_id=",
    DELETE_FILE: "files/delete",
    UPLOAD_FILE: "files/upload",
    UPDATE_FILE: "files/update",
  },
  ALLOWED_FORMATS: [
    "image/jpeg",
    "image/png",
    "image/jpg",
    "image/bmp",
    "image/gif",
    "image/svg+xml",
    "image/tiff",
    "image/webp",
    "application/msword",
    "application/epub+zip",
    "application/gzip",
    "application/java-archive",
    "application/json",
    "application/pdf",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/rtf",
    "application/vnd.ms-excel",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "application/xml",
    "application/zip",
    "application/x-7z-compressed",
    "text/css",
    "text/csv",
    "text/html",
    "text/calendar",
    "text/javascript",
    "text/plain",
    "audio/aac",
    "audio/mpeg",
    "audio/ogg",
    "audio/wav",
    "audio/webm",
    "video/x-msvideo",
    "video/mp4",
    "video/mpeg",
    "video/ogg",
    "video/webm",
    "video/3gpp",
  ],
};
